---

- hosts: all
  become: true
  tasks:

    - name: update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache web server
      apt:
        name: apache2 
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
      
    - name: update repository index
      dnf:
        update_cache: yes
      when: ansible_distribution == "AlmaLinux"

    - name: install apache web server
      dnf:
        name: httpd 
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: add php support for apache
      dnf:
        name: php
        state: latest
      when: ansible_distribution == "AlmaLinux"
