---

- hosts: all
  become: true
  tasks:
    - name: Update repo cache (Almalinux)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false  
      when: ansible_distribution == "AlmaLinux"

    - name: Update repo cache (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: add ssh key for tsimonjero
      tags: always
      authorized_key:
        user: tsimonjero
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM7d7YhaJ8AUGzy3tWGGvLzltMHTjRwdMfG7mle4Vlth ansible"

     
- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Ubuntu servers
      tags: apache, apache2, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for AlmaLinux servers
      tags: apache, almalinux, httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "AlmaLinux"
    
    - name: start httpd (AlmaLinux)
      tags: apache, almalinux, httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "AlmaLinux"

    - name: change e-mail address for admin
      tags: apache, almalinux, httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf 
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution == "AlmaLinux"  

    - name: restart httpd (AlmaLinux)
      tags: apache, httpd, almalinux
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "AlmaLinux"

    - name: copy default html for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
  
- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (almalinux)
      tags: mariadb,db,almalinux
      dnf:
        name:
          - mariadb
        state: latest
      when: ansible_distribution == "almalinux"

    - name: install mariadb server
      tags: ubuntu,db,mariadb
      apt:
        name:
          - mariadb-server
        state: latest
      when: ansible_distribution == "ubuntu"     

      
- hosts: file_servers 
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name:
          - samba
        state: latest

- hosts: workstation
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
     
